<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $version 2 or 3
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$iiifUrl = $plugins->get('iiifUrl');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

?>

<button type="button" class="iiif-copy" title="<?= $escapeAttr($translate('Copy IIIF manifest url in clipboard to use in any IIIF viewer.')) ?>" data-iiif-url="<?= $iiifUrl($resource, '', $version) ?>" data-text-copied="<?= $escapeAttr($translate('IIIF manifest url copied in clipboard!')) ?>" data-text-failed="<?= $translate('Unable to copy url in clipboard!') ?>"></button>
