<?php
// Use the true property, not its internal id (see PropertySelect()).
$properties = [];
$response = $this->api()->search('vocabularies');
foreach ($response->getContent() as $vocabulary) {
    $options = [];
    foreach ($vocabulary->properties() as $property) {
        $options[] = [
            'label' => $property->label(),
            'value' => $property->term(),
        ];
    }
    if (!$options) {
        continue;
    }
    $properties[] = [
        'label' => $vocabulary->label(),
        'options' => $options,
    ];
}
?>
<fieldset id="fieldset-universalviewer-manifest">
    <legend><?php echo $t->translate('Manifest'); ?></legend>
    <p class="explanation">
        <?php echo $t->translate('The plugin creates a manifest for the viewer with elements from each resource (item or item set).'); ?>
        <?php echo $t->translate('The elements below are used when some metadata are missing.'); ?>
        <?php echo $t->translate('In all cases, empty elements are not displayed.'); ?>
        <?php // echo $t->translate('Futhermore, the filter "uv.manifest" is available to change any data.'); ?>
    </p>
    <div class="field">
        <?php
        $select = new Zend\Form\Element\Select('universalviewer_manifest_description_property');
        $select
            ->setLabel($t->translate('Property to use for Attribution'))
            ->setAttribute('id', 'universalviewer_manifest_description_property')
            ->setValue($settings->get('universalviewer_manifest_description_property'))
            ->setEmptyOption($t->translate('Select a property...'))
            ->setValueOptions($properties);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, the first metadata of the record will be added in all manifests and viewers for main description.'); ?>
                    <?php echo $t->translate('It’s recommended to use "Dublin Core:Bibliographic Citation".'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
    <div class="field">
        <?php
        $select = new Zend\Form\Element\Select('universalviewer_manifest_attribution_property');
        $select
            ->setLabel($t->translate('Property to use for Attribution'))
            ->setAttribute('id', 'universalviewer_manifest_attribution_property')
            ->setValue($settings->get('universalviewer_manifest_attribution_property'))
            ->setEmptyOption($t->translate('Select a property...'))
            ->setValueOptions($properties);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
	                <?php echo $t->translate('If any, the first metadata of the resource will be added in all manifests and viewers to indicate the attribution.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_manifest_attribution_default');
            $text->setLabel($t->translate('Default Attribution'));
            $text->setAttribute('id', 'universalviewer_manifest_attribution_default');
            $text->setValue($settings->get('universalviewer_manifest_attribution_default'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, and if there is no metadata for the property above, this text will be added in all manifests and viewers.'); ?>
                    <?php echo $t->translate('It will be used as pop up in the viewer too, if enabled.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
        $select = new Zend\Form\Element\Select('universalviewer_manifest_license_property');
        $select
            ->setLabel($t->translate('Property to use for License'))
            ->setAttribute('id', 'universalviewer_manifest_license_property')
            ->setValue($settings->get('universalviewer_manifest_license_property'))
            ->setEmptyOption($t->translate('Select a property...'))
            ->setValueOptions($properties);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, the first metadata of the resource will be added in all manifests and viewers to indicate the rights.'); ?>
                    <?php echo $t->translate('It’s recommended to use "dcterms:license".'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_manifest_license_default');
            $text->setLabel($t->translate('Default License'));
            $text->setAttribute('id', 'universalviewer_manifest_license_default');
            $text->setValue($settings->get('universalviewer_manifest_license_default'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, and if there is no metadata for the element above, this text will be added in all manifests and viewers to indicate the license.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_manifest_logo_default');
            $text->setLabel($t->translate('Logo'));
            $text->setAttribute('id', 'universalviewer_manifest_logo_default');
            $text->setValue($settings->get('universalviewer_manifest_logo_default'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, this url to an image will be used as logo and displayed in the right panel.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
        $select = new Zend\Form\Element\Select('universalviewer_alternative_manifest_property');
        $select
            ->setLabel($t->translate('Alternative Manifest Property'))
            ->setAttribute('id', 'universalviewer_alternative_manifest_property')
            ->setValue($settings->get('universalviewer_alternative_manifest_property'))
            ->setEmptyOption($t->translate('Select a property...'))
            ->setValueOptions($properties);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('The property supplying the alternative manifest URL for the viewer, for example "dcterms:hasFormat".'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
</fieldset>
<fieldset id="fieldset-universalviewer-embed">
    <legend><?php echo $t->translate('Integration of the viewer'); ?></legend>
    <p class="explanation">
        <?php echo $t->translate('If checked, the viewer will be automatically appended to the item sets or items show page.'); ?>
        <?php echo $t->translate('Else, the viewer can be added via the helper in the theme or the shortcode in any page.'); ?>
    </p>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_set_show');
            $checkbox->setLabel($t->translate('Append to "Item set show"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_set_show');
            $checkbox->setValue($settings->get('universalviewer_append_item_set_show'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_show');
            $checkbox->setLabel($t->translate('Append to "Item show"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_show');
            $checkbox->setValue($settings->get('universalviewer_append_item_show'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <p class="explanation">
        <?php echo $t->translate('These values allows to parameter the integration of the viewer in Omeka pages.'); ?>
        <?php echo $t->translate('The viewer itself can be configured via the file "config.json" and the helper.'); ?>
    </p>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_class');
            $text->setLabel($t->translate('Class of inline frame'));
            $text->setAttribute('id', 'universalviewer_class');
            $text->setValue($settings->get('universalviewer_class'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('Class to add to the inline frame.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_width');
            $text->setLabel($t->translate('Width of inline frame'));
            $text->setAttribute('id', 'universalviewer_width');
            $text->setValue($settings->get('universalviewer_width'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('Keep this field blank to avoid an issue with some themes.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_height');
            $text->setLabel($t->translate('Height of inline frame'));
            $text->setAttribute('id', 'universalviewer_height');
            $text->setValue($settings->get('universalviewer_height'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_locale');
            $text->setLabel($t->translate('Locales of the viewer'));
            $text->setAttribute('id', 'universalviewer_locale');
            $text->setValue($settings->get('universalviewer_locale'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
</fieldset>
<fieldset id="fieldset-universalviewer-background">
    <legend><?php echo $t->translate('Background parameters'); ?></legend>
    <div class="field">
        <?php
            $select = new Zend\Form\Element\Select('universalviewer_iiif_creator');
            $select->setLabel($t->translate('Image processor'));
            $select->setAttribute('id', 'universalviewer_iiif_creator');
            $processors['Auto'] = $t->translate('Automatic (GD when possible, else ImageMagick)');
            $select->setValueOptions($processors);
            $select->setValue($settings->get('universalviewer_iiif_creator'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('Images may be processed internally before to be sent to browser.'); ?>
                    <?php echo $t->translate('Select the one to use.'); ?>
                    <?php echo $t->translate('Generally, GD is quicker than ImageMagick, but ImageMagick manages more formats.'); ?>
                    <?php echo $t->translate('Nevertheless, the performance depends on your installation and your server.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_iiif_max_size');
            $text->setLabel($t->translate('Max dynamic size for images'));
            $text->setAttribute('id', 'universalviewer_iiif_max_size');
            $text->setValue($settings->get('universalviewer_iiif_max_size'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('Set the maximum size in bytes for the dynamic processing of images.'); ?>
                    <?php echo $t->translate('Beyond this limit, the plugin will require a tiled image, for example made by OpenLayersZoom.'); ?>
                    <?php echo $t->translate('Let empty to allow processing of any image.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
</fieldset>
<fieldset id="fieldset-universalviewer-various">
    <legend><?php echo $t->translate('Various parameters'); ?></legend>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_force_https');
            $checkbox->setLabel($t->translate('Force https'));
            $checkbox->setAttribute('id', 'universalviewer_force_https');
            $checkbox->setValue($settings->get('universalviewer_force_https'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('In some cases, the json files (manifest and info) on a secured site (https) contains some urls with the scheme "http".'); ?>
                    <?php echo $t->translate('This option forces all Omeka absolute urls in these files to start with the scheme "https".'); ?>
                    <?php echo $t->translate('Of course, this should be unchecked on a http-only site.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
</fieldset>
