<fieldset id="fieldset-iiifserver-manifest">
    <legend><?php echo $t->translate('IIIF Manifests'); ?></legend>
    <p class="explanation">
        <?php echo $t->translate('The module creates manifests with the properties from each resource (item set, item and media).'); ?>
        <?php echo $t->translate('The properties below are used when some metadata are missing.'); ?>
        <?php echo $t->translate('In all cases, empty properties are not set.'); ?>
        <?php // echo $t->translate('Futhermore, the event "iiif.manifest" is available to change any data.'); ?>
    </p>
    <div class="field">
        <?php
        $select = new Zend\Form\Element\Select('iiifserver_manifest_description_property');
        $select
            ->setLabel($t->translate('Property to use for Description'))
            ->setAttribute('id', 'iiifserver_manifest_description_property')
            ->setValue($settings->get('iiifserver_manifest_description_property'))
            ->setEmptyOption($t->translate('Select a property...'))
            ->setValueOptions($properties);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, the first metadata of the record will be added in all manifests and viewers for main description.'); ?>
                    <?php echo $t->translate('It’s recommended to use "Dublin Core:Bibliographic Citation".'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
    <div class="field">
        <?php
        $select = new Zend\Form\Element\Select('iiifserver_manifest_attribution_property');
        $select
            ->setLabel($t->translate('Property to use for Attribution'))
            ->setAttribute('id', 'iiifserver_manifest_attribution_property')
            ->setValue($settings->get('iiifserver_manifest_attribution_property'))
            ->setEmptyOption($t->translate('Select a property...'))
            ->setValueOptions($properties);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
	                <?php echo $t->translate('If any, the first metadata of the resource will be added in all manifests and viewers to indicate the attribution.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('iiifserver_manifest_attribution_default');
            $text->setLabel($t->translate('Default Attribution'));
            $text->setAttribute('id', 'iiifserver_manifest_attribution_default');
            $text->setValue($settings->get('iiifserver_manifest_attribution_default'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, and if there is no metadata for the property above, this text will be added in all manifests and viewers.'); ?>
                    <?php echo $t->translate('It will be used as pop up in the viewer too, if enabled.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
        $select = new Zend\Form\Element\Select('iiifserver_manifest_license_property');
        $select
            ->setLabel($t->translate('Property to use for License'))
            ->setAttribute('id', 'iiifserver_manifest_license_property')
            ->setValue($settings->get('iiifserver_manifest_license_property'))
            ->setEmptyOption($t->translate('Select a property...'))
            ->setValueOptions($properties);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, the first metadata of the resource will be added in all manifests and viewers to indicate the rights.'); ?>
                    <?php echo $t->translate('It’s recommended to use "dcterms:license".'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('iiifserver_manifest_license_default');
            $text->setLabel($t->translate('Default License'));
            $text->setAttribute('id', 'iiifserver_manifest_license_default');
            $text->setValue($settings->get('iiifserver_manifest_license_default'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, and if there is no metadata for the element above, this text will be added in all manifests and viewers to indicate the license.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('iiifserver_manifest_logo_default');
            $text->setLabel($t->translate('Logo'));
            $text->setAttribute('id', 'iiifserver_manifest_logo_default');
            $text->setValue($settings->get('iiifserver_manifest_logo_default'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, this url to an image will be used as logo and displayed in the right panel.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
        $select = new Zend\Form\Element\Select('iiifserver_alternative_manifest_property');
        $select
            ->setLabel($t->translate('Alternative Manifest Property'))
            ->setAttribute('id', 'iiifserver_alternative_manifest_property')
            ->setValue($settings->get('iiifserver_alternative_manifest_property'))
            ->setEmptyOption($t->translate('Select a property...'))
            ->setValueOptions($properties);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('The property supplying the alternative manifest URL for the viewer, for example "dcterms:hasFormat".'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('iiifserver_manifest_force_https');
            $checkbox->setLabel($t->translate('Force https'));
            $checkbox->setAttribute('id', 'iiifserver_manifest_force_https');
            $checkbox->setValue($settings->get('iiifserver_manifest_force_https'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('In some cases, the json files (manifest and info) on a secured site (https) contains some urls with the scheme "http".'); ?>
                    <?php echo $t->translate('This option forces all Omeka absolute urls in these files to start with the scheme "https".'); ?>
                    <?php echo $t->translate('Of course, this should be unchecked on a http-only site.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
</fieldset>
<fieldset id="fieldset-iiifserver-image">
    <legend><?php echo $t->translate('Image Service'); ?></legend>
    <div class="field">
        <?php
            $select = new Zend\Form\Element\Select('iiifserver_image_creator');
            $select->setLabel($t->translate('Image processor'));
            $select->setAttribute('id', 'iiifserver_image_creator');
            $processors['Auto'] = $t->translate('Automatic (GD when possible, else ImageMagick)');
            $select->setValueOptions($processors);
            $select->setValue($settings->get('iiifserver_image_creator'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('Images may be processed internally before to be sent to browser.'); ?>
                    <?php echo $t->translate('Select the one to use.'); ?>
                    <?php echo $t->translate('Generally, GD is quicker than ImageMagick, but ImageMagick manages more formats.'); ?>
                    <?php echo $t->translate('Nevertheless, the performance depends on your installation and your server.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('iiifserver_image_max_size');
            $text->setLabel($t->translate('Max dynamic size for images'));
            $text->setAttribute('id', 'iiifserver_image_max_size');
            $text->setValue($settings->get('iiifserver_image_max_size'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('Set the maximum size in bytes for the dynamic processing of images.'); ?>
                    <?php echo $t->translate('Beyond this limit, the plugin will require a tiled image, for example made by OpenLayersZoom.'); ?>
                    <?php echo $t->translate('Let empty to allow processing of any image.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
</fieldset>
